### ISSUE TITLE
Duplicate image & transparent image in responsive mode 

### ISSUE THREAD

**Issue by arthurzenika** [datocms/vuejs-demo#5]
Testing out datocms (congrats, the product looks promising!) I found this bug in this demo 

![Screenshot from 2020-11-06 12-36-28](https://user-images.githubusercontent.com/445200/98361957-bc049980-202c-11eb-946b-75baf0f1f5c6.png)

source : https://goofy-bell-c36d47.netlify.app/

**Comment by sistrall** [comment]
Hello @arthurzenika,

I'm sorry I missed this issue: I fixed the problem some months ago.

[Here is the PR](https://github.com/datocms/vuejs-demo/pull/31) containing the fix.
